Repository AY2122S1-CS2103-W14-1/tp, pull requests merged in 2021-11, with the labels that each got.

#229 Fix clear command breaking functionality
  docs/UserGuide.md
  src/main/java/seedu/docit/logic/commands/ClearCommand.java
  src/main/java/seedu/docit/model/Model.java
  src/main/java/seedu/docit/model/ModelManager.java
  src/test/java/seedu/docit/testutil/stubs/ModelStub.java
Labels: bugfix

#232 Fix documentation errors and prescription input/duplicate bug
  docs/UserGuide.md
  src/main/java/seedu/docit/commons/core/Messages.java
  src/main/java/seedu/docit/logic/parser/AddressBookParser.java
  src/main/java/seedu/docit/model/appointment/Appointment.java
  src/test/java/seedu/docit/logic/parser/AddressBookParserTest.java
Labels: bugfix

#236 Fix multiple PED bugs, more restrictive parsers, UG expected outcomes for Appointments
  docs/UserGuide.md
  src/main/java/seedu/docit/logic/commands/ArchiveAppointmentCommand.java
  src/main/java/seedu/docit/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/docit/logic/parser/ParserUtil.java
  src/main/java/seedu/docit/model/patient/Address.java
  src/main/java/seedu/docit/model/patient/MedicalHistory.java
  src/main/java/seedu/docit/model/patient/Name.java
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/docit/model/person/AddressTest.java
  src/test/java/seedu/docit/model/person/NameTest.java
Labels: bugfix

#238 Fix context-menu font color and `exit` procedure
  src/main/java/seedu/docit/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
Labels: bugfix

#240 Update Medical History documentation in UserGuide
  docs/UserGuide.md
Labels: documentation

#251 Fix weird inputs for add medical history
  docs/UserGuide.md
  src/main/java/seedu/docit/logic/commands/DeleteMedicalEntryCommand.java
  src/main/java/seedu/docit/logic/parser/ParserUtil.java
Labels: bugfix

#252 Add Prescription documentation
  docs/UserGuide.md
  src/main/java/seedu/docit/logic/commands/prescription/AddPrescriptionCommand.java
  src/main/java/seedu/docit/logic/commands/prescription/DeletePrescriptionCommand.java
Labels: documentation

#255 Fix Patient Command Table in User Guide
  docs/UserGuide.md
Labels: documentation, bugfix

#260 Update New Feature of PPP
  docs/team/gycgabriel.md
Labels: documentation

#291 Update Gabriel's PPP
  docs/team/gycgabriel.md
Labels: documentation

#293 Update DG for Appointments for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentClassDiagram.puml
  docs/diagrams/DeletePatientActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AppointmentClassDiagram.png
  docs/images/DeletePatientActivityDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#304 Update sequence diagrams
  docs/diagrams/AddMedicalEntryFeatureSequenceDiagram.png
  docs/diagrams/AddMedicalEntryFeatureSequenceDiagram.puml
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram.png
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram.puml
  docs/diagrams/DeletePatientFeatureSequenceDiagram.png
  docs/diagrams/DeletePatientFeatureSequenceDiagram.puml
Labels: documentation

#309 Shorten Didy PPP
  docs/team/didymental.md
Labels: documentation

#312 Shorten Didy PPP even more
  docs/team/didymental.md
Labels: documentation

#316 Update sequence diagrams
  docs/diagrams/AddMedicalEntryFeatureSequenceDiagram.png
  docs/diagrams/AddMedicalEntryFeatureSequenceDiagram.puml
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram.png
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram.puml
  docs/diagrams/DeletePatientFeatureSequenceDiagram.png
  docs/diagrams/DeletePatientFeatureSequenceDiagram.puml
  docs/team/didymental.md
Labels: documentation

#317 Update DG for Appointments
  docs/DeveloperGuide.md
  docs/diagrams/DeletePatientActivityDiagram.puml
  docs/images/DeletePatientActivityDiagram.png
Labels: documentation

#322 Update DG for Appointment Use Case, Test cases
  docs/DeveloperGuide.md
  src/main/java/seedu/docit/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/docit/logic/parser/EditAppointmentCommandParser.java
  src/test/java/seedu/docit/logic/parser/AddAppointmentCommandParserTest.java
Labels: documentation

#321 Add manual test cases, NFR, use cases, update sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddMedicalEntryFeatureSequenceDiagram.png
  docs/diagrams/AddMedicalEntryFeatureSequenceDiagram.puml
  docs/diagrams/AddMedicalEntrySequenceFeatureDiagram1.png
  docs/diagrams/AddMedicalEntrySequenceFeatureDiagram1.puml
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram.png
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram.puml
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram1.png
  docs/diagrams/DeleteMedicalEntryFeatureSequenceDiagram1.puml
  docs/diagrams/DeletePatientFeatureSequenceDiagram.png
  docs/diagrams/DeletePatientFeatureSequenceDiagram.puml
  docs/diagrams/DeletePatientFeatureSequenceDiagram1.png
  docs/diagrams/DeletePatientFeatureSequenceDiagram1.puml
  docs/team/didymental.md
Labels: documentation

#323 Update Gabriel's PPP
  docs/DeveloperGuide.md
  docs/team/gycgabriel.md
Labels: documentation

#325 Shorten Gabriel's PPP
  docs/team/gycgabriel.md
Labels: documentation

#327 Minor fixes to Gabriel's PPP
  docs/UserGuide.md
  docs/team/gycgabriel.md
  src/main/java/seedu/docit/logic/parser/ParserUtil.java
  src/test/java/seedu/docit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/docit/logic/parser/AddAppointmentCommandParserTest.java
Labels: documentation

#331 Parser allow special character
  docs/DeveloperGuide.md
  docs/team/huyuxin0429.md
  src/main/java/seedu/docit/logic/parser/AddressBookParser.java
Labels: bugfix

#329 Add images to UG and navigating section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AppointmentView.png
  docs/images/CommandBox.png
  docs/images/CommandResultStatusDisplay.png
  docs/images/DocHelp.png
  docs/images/DocitHeader.png
  docs/images/Navigability.png
  docs/images/PatientView.png
  docs/images/PtAdd.png
  docs/images/PtDelete.png
  docs/images/PtEdit.png
  docs/images/PtList.png
  docs/images/PtMa.png
  docs/images/PtMd.png
  src/main/java/seedu/docit/logic/commands/AddMedicalEntryCommand.java
  src/main/java/seedu/docit/logic/parser/ParserUtil.java
  src/main/java/seedu/docit/model/patient/MedicalHistory.java
  src/main/java/seedu/docit/model/patient/Patient.java
  src/main/java/seedu/docit/model/patient/exceptions/ExceedCharacterLimit.java
  src/main/java/seedu/docit/model/patient/exceptions/TooManyMedicalEntriesException.java
  src/main/resources/view/PatientListCard.fxml
Labels: documentation
